const colors = require("tailwindcss/colors");

module.exports = {
  // mode: 'jit', // Add Just In Time Mode
  purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    letterSpacing: {
      tightest: "-.075em",
      tighter: "-.05em",
      tight: "-.025em",
      normal: "0",
      wide: ".025em",
      wider: ".05em",
      widest: ".1em",
      widest: ".25em",
    },
    extend: {
      fontFamily: {
        serif: ["Roboto", "Helvetica", "Arial", "sans-serif"],
      },
      spacing: {
        15: "7.5rem",
        100: "28rem",
        128: "32rem",
        144: "36rem",
        196: "38rem",
        210: "40rem",
        728: "45.5rem", //tamanho do figma
        500: "50rem",
        364: "60rem",
        405: "80rem",
        1440: "90rem",
        1540: "110rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
    },
    colors: {
      // Now we build the full color palette, using all colors available
      // as shown at this link: https://tailwindcss.com/docs/customizing-colors#color-palette-reference
      transparent: "transparent",
      current: "currentColor",
      primaryGreen: "#12AD99",
      green: "#299c93",
      green1: "#219653",
      green2: "#279E94",
      green5: "#B1EAE2",
      primaryBlue: "#1786C2",
      blue: "1685C1",
      blue2: "#10AFE0",
      blue4: "#B8E8F4",
      primaryBlack: "#1F1F1F",
      black: "#000",
      black2: "#2F2F2F",
      graybody: "#F3F3F3",
      gray1: "#4F4F4F",
      gray2: "#4F4F4F",
      gray3: "#828282",
      gray4: "#BDBDBD",
      gray5: "#E0E0E0",
      gray6: "#F2F2F2",
      bluegray: colors.blueGray,
      coolgray: colors.coolGray,
      gray: colors.gray,
      truegray: colors.trueGray,
      warmgray: colors.warmGray,
      primaryYellow: "#FFA11C",
      purple: colors.purple,
      purple: "#B783FA",
      purple2: "#BB6BD9",
      white: colors.white,
      white2: "#FFF",
      red: "#EF4444",
      red5: "#F99B9B",
      orange: "#FF7A2E",
      amber: colors.amber,
      yellow: "#F2C94C",
      lime: colors.lime,
      brown: "#AD8D43",
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      indigo: colors.indigo,
      violet: colors.violet,
      fuchsia: colors.fuchsia,
      pink: "#FF99C5",
      rose: colors.rose,
      cinza: "#FAFAFA",
    },
  },
  variants: {
    extend: {
      textColor: ["active", "checked"],
      backgroundColor: ["active", "visited"],
    },
  },
  plugins: [require("@tailwindcss/line-clamp")],
};
